### ISSUE TITLE
Can the project support python2.7/3.3/3.4

### ISSUE THREAD

**Issue by wwqgtxx** [karellen/karellen-geventws#17]
Because of many reason,we need to use different version python runtime to work.And the old gevent-websocket project had no update long times.So as a user want to know can this project support python2.7/3.3/3.4 like the gevent project.It will also help us use will with Flask-SocketIO.

**Comment by arcivanov** [comment]
I'll see what I can do.

**Comment by arcivanov** [comment]
@wwqgtxx I suspect that 2.7 will not happen due to str/unicode changes. 
3.3 and 3.4 will likely be possible. For 2.7 you can use the original [gevent-websocket](https://pypi.python.org/pypi/gevent-websocket/).

**Comment by arcivanov** [comment]
I can confirm that tests pass on 3.3, 3.4 and 3.5. I'll make a documentation change.

**Comment by wwqgtxx** [comment]
Can confirm that tests pass on 2.7 too?
Now I use the `requestments.txt` to solve this problem
```txt
karellen-geventws>=1.0.1 ; python_version > '3.2'
gevent-websocket ; python_version < '3'
```
But I want to only use one package to avoid the different with `karellen-geventws` and `gevent-websocket` causing some other problem.

And two other questions:
Why the now version is `1.0.2.dev20161215225056` in pypi? 
It let the user fell that this package was a unstable package.

Does the package name should use `geventwebsocket`?
When the user install `karellen-geventws` and `gevent-websocket` both in some reason.It well cause confusion.I suggest that providing a `monkey_patch()` function to send the package namespace to `geventwebsocket`.At the other time,use another package namespace like `geventws` or `karellen-geventws`.

**Comment by arcivanov** [comment]
No they do not, 2.7 is not supported. Please use gevent-websocket for 2.x.
