### ISSUE TITLE
send_frame should handle empty and non-binary application data in ping per 5.5.2

### ISSUE THREAD

**Issue by bugslife** [karellen/karellen-geventws#22]
It seems that ping which send a header but an empty message fails to concat because of impossible 
type concat: bytes+str

I've added a guard for this and ignore empty messages in send_frame:

    def send_frame(self, message, opcode):
        """
        Send a frame over the websocket with message as its payload
        """
        if self.closed:
            self.current_app.on_close(MSG_ALREADY_CLOSED)
            raise WebSocketError(MSG_ALREADY_CLOSED)

        if opcode == self.OPCODE_TEXT:
            message = self._encode_bytes(message)
        elif opcode == self.OPCODE_BINARY:
            message = bytes(message)

        header = Header.encode_header(True, opcode, '', len(message), 0)

        try:
            # (Chen.M: Added a guard on empty message such as a ping, concatenating header+message will raise an exception because of trying to concat bytes+str )
            payload = header + message if message else header
            self.raw_write(payload)

        except error:
            raise WebSocketError(MSG_SOCKET_DEAD)

**Comment by arcivanov** [comment]
Thanks!
